var itinerary = [
    '1/1',  'Maui, HI',
    '1/4',  'Honolulu, HI',
    '1/8',  'Seattle, WA',
    '1/14', 'Auckland, NZ',
    '1/20', 'Tauranga, NZ',
    '1/22', 'Waitomo, NZ',
    '1/23', 'Rotorua, NZ',
    '1/25', 'Napier, NZ',
    '1/26', 'Wellington, NZ',
    '1/29', 'Nelson, NZ',
    '1/31', 'Fox Glacier, NZ',
    '2/1',  'Wanaka, NZ',
    '2/2',  'Queenstown, NZ',
    '2/6',  'Christchurch, NZ',
    '2/7',  'Brisbane, AU',
    '2/8',  'Cruise in AU',
    '2/15', 'Brisbane, AU',
    '2/17', 'Gold Coast, AU',
    '2/23', 'Byron Bay, AU',
    '3/1', 'Sydney, AU',
    '3/12', 'Melbourne, AU',
    '4/1', 'Noosa, AU',
    '4/9', 'Cairns, AU',
    '4/16', 'Hiroshima, JP',
    '4/20', 'Osaka, JP',
    '4/24', 'Kyoto, JP',
    '4/29', 'Tokyo, JP',
    '5/27', 'Frankfurt, DE',
    '6/3', 'Seattle, WA',
    '7/11', 'San Diego, CA',
    '7/25', 'Stockholm, SE',
    '8/1', 'Brussels, BE',
    '8/4', 'Amsterdam, NE',
    '8/8', 'Den Haag, NE',
    '8/11', 'Paris, FR',
    '8/17', 'Prague, CZ',
    '8/28', 'Krakow, PL',
    '9/3', 'Budapest, HU',
    '9/7', 'Vienna, AT',
    '9/13', 'Florence, IT',
    '9/19', 'Rome, IT',
    '9/23', 'Santorini, GR',
    '10/1', 'Athens, GR',
    '10/3', 'Hong Kong, HK',
    '10/25', 'Bali, ID',
    '12/16', 'Bangkok, TH',
    '12/20', 'Koh Phangan, TH',
    '12/27', 'Bangkok, TH',
    '1/2', 'Chiang Mai, TH',
    '2/13', 'Bali, ID',
    '2/28', 'Da Nang, VN',
    '3/12', 'Singapore',
    '3/18', 'Phuket, TH',
    '3/21', 'Tokyo, JP',
    '4/8', 'Chiang Mai, TH',
    '5/9', 'Kuala Lumpur, MY',
    '5/12', 'Krabi, TH',
    '5/13', 'Ko Lanta, TH',
    '5/22', 'Frankfurt, DE',
    '5/31', 'Tallinn, EE'
];